rsa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from core.views import *


urlpatterns = patterns('',
    # Examples:
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^contato/$', 'core.views.contato', name='contato'),
    url(r'^eventos/$', EventoList.as_view(), name='evento_list'),
    url(r'^eventos/add/$', EventoCreate.as_view(), name='evento_add'),
    url(r'^eventos/edit/(?P<pk>\d+)/$', EventoUpdate.as_view(), name='evento_update'),
    url(r'^eventos/(?P<pk>\d+)/$', EventoDetail.as_view(), name='evento_detail'),
    url(r'^eventos/delete/(?P<pk>\d+)/$', EventoDelete.as_view(), name='evento_del'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^criar-conta/$', UsuarioCreate.as_view(), name='usuario_add'),

    url(r'auth/', include('django.contrib.auth.urls', namespace='auth')),

    url(r'^admin/', include(admin.site.urls)),
)

core/models.py
# coding: utf-8
from datetime import datetime
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User, AbstractUser, BaseUserManager
import reversion

STATUS = (
    ('Ativo', 'Ativo'),
    ('Inativo', 'Inativo'),
)

@reversion.register
class CommonModel(models.Model):
    data_criacao = models.DateTimeField(default=datetime.now, auto_now_add=True)
    data_atualizacao = models.DateTimeField(default=datetime.now, auto_now=True)
    status = models.CharField(max_length=20, default='Ativo', choices=STATUS)

    class Meta:
        abstract = True

@reversion.register
class Evento(CommonModel):

    titulo = models.CharField(max_length=100)
    conteudo = models.TextField()
    data_inicio = models.DateField()
    data_fim = models.DateField()
    inscricao = models.BooleanField(default=True,
                                    help_text='O evento vai ter inscrição?')

    data_inicio_inscricao = models.DateField(blank=True, null=True)
    data_fim_inscricao = models.DateField(blank=True, null=True)

    local = models.CharField(max_length=100, default='IFPI')
    site = models.URLField(blank=True, null= True)

    local_inscricao = models.CharField(max_length=100, blank=True, null= True)
    site_inscricao = models.URLField(blank=True, null= True)


    # user = models.ForeignKey(User, blank= True, null=True)

    def __unicode__(self):
        return self.titulo

    class Meta:
        ordering = ['-data_criacao', '-data_atualizacao']
        verbose_name = 'Evento'
        verbose_name_plural = 'Eventos'


class Participante(CommonModel):
    nome = models.CharField(max_length=100)
    email = models.EmailField()
    evento = models.ForeignKey(Evento)


class Blog(CommonModel):
    nome = models.CharField(max_length=50)


class CustomUserManager(BaseUserManager):

    def create_user(self, matricula, email, password=None):
        if not matricula:
            raise ValueError("Matricula nao definida")
        user = self.model(matricula=matricula, email=email)
        user.set_password(password)
        user.is_staff = True
        user.save(using=self.db)
        return user

    def create_superuser(self, matricula, email, password):
        user = self.create_user(matricula, email, password=password)
        user.is_superuser = True
        user.save(using=self.db)
        return user


class Usuario(AbstractUser):

    matricula = models.CharField(max_length=10, unique=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'matricula'

core/forms.py
from django import forms
from core.models import Evento, Usuario

class ContatoForm(forms.Form):
    nome = forms.CharField(max_length=50)
    email = forms.EmailField()
    mensagem = forms.CharField(widget=forms.Textarea)


class EventoStatus(forms.ModelForm):


    class Meta:
        model = Evento
        fields = ('status', )


class UsuarioForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    def save(self, commit=True):
        user = super(UsuarioForm, self).save(commit=False)
        user.set_password(self.data['password'])
        user.is_staff = True
        user.is_active = True
        if commit:
            user.save()
        return user

    class Meta:
        model = Usuario
        fields = ('matricula', 'email', 'password', 'username', 'first_name')

core/views.py
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.shortcuts import render
from core.forms import ContatoForm, UsuarioForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from core.models import Evento, Usuario
from core.forms import EventoStatus
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import permission_required, user_passes_test
from django.utils.decorators import method_decorator

class LoginMixin(object):

    @classmethod
    def as_view(cls, **kwargs):
        view = super(LoginMixin, cls).as_view(**kwargs)
        return login_required(view)


class EventoList(LoginMixin, ListView):
    model = Evento
    paginate_by = 2


class EventoDetail(LoginMixin, DetailView):
    model = Evento

class HomeView(LoginMixin, TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['eventos_count'] = Evento.objects.count()
        return context


def grupo_eventos(usuario):
    if usuario:
        return usuario.groups.filter(name='Assessoria de Imprensa').exists()
    return False

class EventoCreate(LoginMixin, SuccessMessageMixin, CreateView):
    model = Evento
    success_url = '/eventos/'
    success_message = '%(titulo)s criado com sucesso'

    @method_decorator(user_passes_test(grupo_eventos))
    def dispatch(self, *args, **kwargs):
        return super(EventoCreate, self).dispatch(*args, **kwargs)


class EventoUpdate(LoginMixin, SuccessMessageMixin, UpdateView):
    model = Evento
    success_url = '/eventos/'
    success_message = '%(titulo)s alterado com sucesso'

    @method_decorator(permission_required('core.change_evento'))
    def dispatch(self, *args, **kwargs):
        return super(EventoUpdate, self).dispatch(*args, **kwargs)


class EventoDelete(DeleteView):
    model = Evento
    success_url = '/eventos/'


class UsuarioCreate(CreateView):
    model = Usuario
    success_url = '/'
    form_class = UsuarioForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(UsuarioCreate, self).dispatch(*args, **kwargs)


@login_required
def contato(request):

    form = ContatoForm(request.POST or None)

    if form.is_valid() and request.method == 'POST':
        nome = form.cleaned_data['nome']
        email = form.cleaned_data['email']
        mensagem = form.cleaned_data['mensagem']
        print nome, email
        send_mail('Mensagem enviada por %s' % nome, mensagem, email,
                  ['gabriel@128bits.cc', 'gabrielfreitas07@gmail.com'] )

    return render(request, 'contato.html', {'form':form})

rsa/views.py
# coding: utf-8
from django.shortcuts import render

def home(request):
    return render(request, "index.html", {'q': 'IFPI'})

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Bootstrap Admin Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{ STATIC_URL }}bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{{ STATIC_URL }}bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- DataTables CSS -->
    <link href="{{ STATIC_URL }}bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="{{ STATIC_URL }}bower_components/datatables-responsive/css/dataTables.responsive.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{ STATIC_URL }}dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{{ STATIC_URL }}bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        {% include "components/menu.html" %}


        <div id="page-wrapper">

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
            {% endif %}


            {% block content %}
            {% endblock %}
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="{{ STATIC_URL }}bower_components/jquery/dist/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ STATIC_URL }}bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{{ STATIC_URL }}bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="{{ STATIC_URL }}bower_components/datatables/media/js/jquery.dataTables.min.js"></script>
    <script src="{{ STATIC_URL }}bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{{ STATIC_URL }}dist/js/sb-admin-2.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>

</body>

</html>

templates/components/menu.html
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">RSA</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">

                <li>{{ eventos_count }} eventos</li>
                <li>{{ eventos_ativos }} eventos ativos</li>
                <li>{{ usuarios_count }} usuários</li>

                <li>Olá {{ user }}, seja bem-vindo!</li>

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>Read All Messages</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-messages -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-tasks">
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 1</strong>
                                        <span class="pull-right text-muted">40% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                            <span class="sr-only">40% Complete (success)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 2</strong>
                                        <span class="pull-right text-muted">20% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                            <span class="sr-only">20% Complete</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 3</strong>
                                        <span class="pull-right text-muted">60% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                            <span class="sr-only">60% Complete (warning)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 4</strong>
                                        <span class="pull-right text-muted">80% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                            <span class="sr-only">80% Complete (danger)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Tasks</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-tasks -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-comment fa-fw"></i> New Comment
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="pull-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> Message Sent
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-tasks fa-fw"></i> New Task
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'auth:logout' %}?next={% url 'home' %}">
                                <i class="fa fa-sign-out fa-fw"></i> Logout</a>
                            </li>
                        {% else %}
                            <li><a href="{% url 'auth:login' %}?next={% url 'home' %}">
                                <i class="fa fa-sign-out fa-fw"></i> Login</a>
                            </li>
                        {% endif %}
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="/"><i class="fa fa-dashboard fa-fw"></i> Home</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Eventos<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'evento_list' %}">Listagem</a>
                                </li>
                                <li>
                                    <a href="{% url 'evento_add' %}">Adicionar</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

templates/contato.html
<form action="{% url 'contato' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>

templates/core/evento_confirm_delete.html
<p>Você tem certeza?</p>
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="confirmar">
</form>

templates/core/evento_detail.html
<h1>{{ object.titulo|capfirst }}</h1>
<p>Descrição: {{ object.descricao }}</p>
<ul>
    <li>Data início: {{ object.data_inicio|date:"d/m/Y" }}</li>
    <li>Data fim: {{ object.data_fim }}</li>
    <li>Site: {{ object.site }}</li>
    <li>Local: {{ object.local }}</li>
</ul>

templates/core/evento_form.html
{% extends 'base.html' %}

{% load helper %}

{% block content %}

<form method="post" role="form">
    {% csrf_token %}
    {% for campo in form %}
        <div class="form-group {% if campo.errors %}has-error{% endif %}">
            <label class="control-label">
                {{ campo.label }}
            </label>
            {{ campo|addclass:"form-control" }}

            <p class="help-block">{{ campo.help_text }}</p>
            {% if campo.errors %}
                {% for error in campo.errors %}
                <p class="help-block">{{ error }}</p>
                {% endfor %}
            {% endif %}
        </div>
    {% endfor %}

    <input type="submit" value="Enviar">
</form>

{% endblock %}

templates/core/evento_list.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Eventos</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>

    {% if perms.core.add_evento %}

    <a href="{% url 'evento_add' %}" class="btn btn-success btn-large">Adicionar</a>
    <hr>
    {% endif %}



<table class="table table-striped table-bordered table-hover">
{% for evento in object_list %}
    <tr>
        <td>
            <a href="{% url 'evento_detail' evento.pk %}">{{ evento.titulo }}</a>
        </td>
        <td>
            {{ evento.local }}
        </td>
        <td>
          <a href="{% url 'evento_update' evento.pk %}">Editar</a>
        </td>
        <td>
            <a href="{% url 'evento_del' evento.pk %}">Deletar</a>
        </td>
    </tr>
{% endfor %}
</table>
        {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="paginate_button previous">
                    <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                </li>
            {% endif %}

            {% for page in page_obj.paginator.page_range %}
                {% ifequal page page_obj.number %}
                    <li class="paginate_button active"><a href="#">{{ page }}</a></li>
                {% else %}
                    <li class="paginate_button"><a href="?page={{ page }}">{{ page }}</a></li>
                {% endifequal %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="paginate_button next">
                <a href="?page={{ page_obj.next_page_number }}">Próxima</a>
            </li>
            {% endif %}
        </ul>
        {% endif %}

{% endblock %}

templates/core/usuario_form.html
{% extends 'base.html' %}

{% load helper %}

{% block content %}

<form method="post" role="form">
    {% csrf_token %}
    {% for campo in form %}
        <div class="form-group">
            <label>{{ campo.label }}</label>
            {{ campo|addclass:"form-control" }}
            <p class="help-block">{{ campo.help_text }}</p>
        </div>
    {% endfor %}

    <input type="submit" value="Enviar">
</form>

{% endblock %}